import ReportImage from "./ReportImage"

export default function ReportPage() {
    return (
        <div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-2">

                    </div>
                    <div class="col-8">
                        <figure class="text-center my-5">
                            <h1 class="display-2">Title Of The Report</h1>
                            <img class="rounded-circle shadow my-3" src="http://lavinephotography.com.au/wp-content/uploads/2017/01/PROFILE-Photography-112.jpg" alt="Profile picture" style={{"width": "80px", "height": "80px"}}></img>
                            <p class="lead">Bella</p>
                        </figure>
                        <p class="lead">Updated Aug 12, 2021, 12:48pm EDT</p>
                        <hr class="bg-secondary border-2 border-top border-secondary"></hr>
                        <figure class="text-center my-5">
                            <p class="fw-normal lh-base">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat imperdiet sed euismod nisi porta. Amet purus gravida quis blandit turpis cursus. Consectetur adipiscing elit ut aliquam purus sit amet. Varius morbi enim nunc faucibus a. Bibendum est ultricies integer quis. Mauris augue neque gravida in fermentum et sollicitudin ac orci. Tincidunt eget nullam non nisi. Eu scelerisque felis imperdiet proin fermentum leo vel. Volutpat est velit egestas dui. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Magna fringilla urna porttitor rhoncus dolor purus non. Ornare suspendisse sed nisi lacus sed viverra tellus in. Vitae aliquet nec ullamcorper sit.</p>
                                
                            <p class="fw-normal lh-base">In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Convallis aenean et tortor at risus viverra adipiscing at. Morbi tristique senectus et netus et. Imperdiet massa tincidunt nunc pulvinar. Habitant morbi tristique senectus et netus et malesuada. Laoreet sit amet cursus sit amet dictum. Proin sed libero enim sed faucibus. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Pellentesque id nibh tortor id. Lectus nulla at volutpat diam ut venenatis. Curabitur vitae nunc sed velit dignissim sodales ut eu.</p>

                            <p class="fw-normal lh-base">Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Aliquam ut porttitor leo a diam. Sit amet facilisis magna etiam tempor orci eu lobortis. Facilisis sed odio morbi quis. Ac felis donec et odio pellentesque diam volutpat. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Gravida quis blandit turpis cursus in hac habitasse. Id consectetur purus ut faucibus. Tellus cras adipiscing enim eu turpis egestas. Enim lobortis scelerisque fermentum dui faucibus in ornare. Et leo duis ut diam quam nulla porttitor massa id.</p>

                            <p class="fw-normal lh-base">Bibendum arcu vitae elementum curabitur vitae nunc sed. Praesent semper feugiat nibh sed. Tristique magna sit amet purus gravida quis blandit turpis cursus. In tellus integer feugiat scelerisque varius morbi. Sed faucibus turpis in eu mi bibendum neque. Ornare lectus sit amet est placerat in egestas erat imperdiet. Enim nunc faucibus a pellentesque sit amet. At quis risus sed vulputate odio. Neque ornare aenean euismod elementum nisi quis eleifend quam. Fermentum odio eu feugiat pretium nibh ipsum. Leo vel fringilla est ullamcorper eget nulla. Amet nulla facilisi morbi tempus. Est pellentesque elit ullamcorper dignissim cras. Ut morbi tincidunt augue interdum velit euismod. Ultrices eros in cursus turpis massa tincidunt. Leo vel fringilla est ullamcorper eget nulla. Ullamcorper a lacus vestibulum sed. Ipsum a arcu cursus vitae congue mauris rhoncus. Malesuada fames ac turpis egestas maecenas pharetra convallis. Aliquet nibh praesent tristique magna sit amet.</p>

                            <p class="fw-normal lh-base">Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Nunc mattis enim ut tellus elementum. Sed turpis tincidunt id aliquet risus feugiat in ante. Ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Donec enim diam vulputate ut. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Scelerisque purus semper eget duis at tellus. Feugiat in ante metus dictum at tempor commodo. Nulla malesuada pellentesque elit eget gravida. Mi sit amet mauris commodo. Sapien eget mi proin sed libero enim sed faucibus. At risus viverra adipiscing at in tellus integer feugiat scelerisque. At erat pellentesque adipiscing commodo elit at imperdiet dui. At erat pellentesque adipiscing commodo. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Risus quis varius quam quisque id diam vel. Platea dictumst vestibulum rhoncus est pellentesque elit.</p>

                            <p class="fw-normal lh-base">Tristique senectus et netus et malesuada fames ac turpis egestas. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Justo donec enim diam vulputate ut. Viverra orci sagittis eu volutpat odio. Eget magna fermentum iaculis eu non diam phasellus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Quis risus sed vulputate odio ut enim blandit. Commodo viverra maecenas accumsan lacus vel facilisis. Velit egestas dui id ornare arcu odio ut sem nulla. Sed sed risus pretium quam vulputate dignissim suspendisse. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Placerat vestibulum lectus mauris ultrices. A lacus vestibulum sed arcu non odio euismod. Elit scelerisque mauris pellentesque pulvinar pellentesque. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. At in tellus integer feugiat scelerisque. Amet justo donec enim diam vulputate ut pharetra sit amet. Ac auctor augue mauris augue.</p>

                            <p class="fw-normal lh-base">Semper auctor neque vitae tempus quam pellentesque. Ultricies tristique nulla aliquet enim tortor at auctor. Morbi tristique senectus et netus et malesuada fames ac turpis. Eu lobortis elementum nibh tellus molestie. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Sagittis vitae et leo duis ut diam. Fames ac turpis egestas integer. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. In eu mi bibendum neque egestas congue quisque. Enim sit amet venenatis urna cursus. Elementum sagittis vitae et leo. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Neque aliquam vestibulum morbi blandit. Sodales ut eu sem integer vitae justo. Tristique sollicitudin nibh sit amet commodo nulla facilisi.</p>

                            <p class="fw-normal lh-base">Tempor id eu nisl nunc mi ipsum. Nulla aliquet porttitor lacus luctus. Nisl rhoncus mattis rhoncus urna neque. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Lorem mollis aliquam ut porttitor leo a diam. Eget magna fermentum iaculis eu non diam phasellus vestibulum. A condimentum vitae sapien pellentesque habitant morbi tristique. Odio eu feugiat pretium nibh ipsum consequat. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et. Et pharetra pharetra massa massa ultricies mi. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Venenatis cras sed felis eget velit aliquet sagittis id consectetur. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sit amet nisl purus in mollis nunc. Dolor sit amet consectetur adipiscing elit duis. Augue mauris augue neque gravida.</p>

                            <p class="fw-normal lh-base">Magna etiam tempor orci eu lobortis elementum nibh tellus. Ut diam quam nulla porttitor massa. Nibh praesent tristique magna sit amet purus gravida. Suspendisse in est ante in nibh. Non nisi est sit amet facilisis. Scelerisque eu ultrices vitae auctor eu augue ut. Turpis tincidunt id aliquet risus. Porttitor leo a diam sollicitudin. Vulputate ut pharetra sit amet aliquam id diam maecenas. Id faucibus nisl tincidunt eget nullam. Nulla facilisi cras fermentum odio eu feugiat pretium. Erat pellentesque adipiscing commodo elit at imperdiet. Ultrices in iaculis nunc sed augue lacus viverra vitae. Nunc id cursus metus aliquam eleifend. Tellus molestie nunc non blandit massa enim nec dui. Accumsan lacus vel facilisis volutpat. Viverra justo nec ultrices dui.</p>

                                <ReportImage/>
                                <p class="fw-normal lh-base">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat imperdiet sed euismod nisi porta. Amet purus gravida quis blandit turpis cursus. Consectetur adipiscing elit ut aliquam purus sit amet. Varius morbi enim nunc faucibus a. Bibendum est ultricies integer quis. Mauris augue neque gravida in fermentum et sollicitudin ac orci. Tincidunt eget nullam non nisi. Eu scelerisque felis imperdiet proin fermentum leo vel. Volutpat est velit egestas dui. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Magna fringilla urna porttitor rhoncus dolor purus non. Ornare suspendisse sed nisi lacus sed viverra tellus in. Vitae aliquet nec ullamcorper sit.</p>
                                
                            <p class="fw-normal lh-base">In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Convallis aenean et tortor at risus viverra adipiscing at. Morbi tristique senectus et netus et. Imperdiet massa tincidunt nunc pulvinar. Habitant morbi tristique senectus et netus et malesuada. Laoreet sit amet cursus sit amet dictum. Proin sed libero enim sed faucibus. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Pellentesque id nibh tortor id. Lectus nulla at volutpat diam ut venenatis. Curabitur vitae nunc sed velit dignissim sodales ut eu.</p>

                            <p class="fw-normal lh-base">Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Aliquam ut porttitor leo a diam. Sit amet facilisis magna etiam tempor orci eu lobortis. Facilisis sed odio morbi quis. Ac felis donec et odio pellentesque diam volutpat. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Gravida quis blandit turpis cursus in hac habitasse. Id consectetur purus ut faucibus. Tellus cras adipiscing enim eu turpis egestas. Enim lobortis scelerisque fermentum dui faucibus in ornare. Et leo duis ut diam quam nulla porttitor massa id.</p>

                            <p class="fw-normal lh-base">Bibendum arcu vitae elementum curabitur vitae nunc sed. Praesent semper feugiat nibh sed. Tristique magna sit amet purus gravida quis blandit turpis cursus. In tellus integer feugiat scelerisque varius morbi. Sed faucibus turpis in eu mi bibendum neque. Ornare lectus sit amet est placerat in egestas erat imperdiet. Enim nunc faucibus a pellentesque sit amet. At quis risus sed vulputate odio. Neque ornare aenean euismod elementum nisi quis eleifend quam. Fermentum odio eu feugiat pretium nibh ipsum. Leo vel fringilla est ullamcorper eget nulla. Amet nulla facilisi morbi tempus. Est pellentesque elit ullamcorper dignissim cras. Ut morbi tincidunt augue interdum velit euismod. Ultrices eros in cursus turpis massa tincidunt. Leo vel fringilla est ullamcorper eget nulla. Ullamcorper a lacus vestibulum sed. Ipsum a arcu cursus vitae congue mauris rhoncus. Malesuada fames ac turpis egestas maecenas pharetra convallis. Aliquet nibh praesent tristique magna sit amet.</p>

                            <p class="fw-normal lh-base">Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Nunc mattis enim ut tellus elementum. Sed turpis tincidunt id aliquet risus feugiat in ante. Ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Donec enim diam vulputate ut. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Scelerisque purus semper eget duis at tellus. Feugiat in ante metus dictum at tempor commodo. Nulla malesuada pellentesque elit eget gravida. Mi sit amet mauris commodo. Sapien eget mi proin sed libero enim sed faucibus. At risus viverra adipiscing at in tellus integer feugiat scelerisque. At erat pellentesque adipiscing commodo elit at imperdiet dui. At erat pellentesque adipiscing commodo. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Risus quis varius quam quisque id diam vel. Platea dictumst vestibulum rhoncus est pellentesque elit.</p>

                            <p class="fw-normal lh-base">Tristique senectus et netus et malesuada fames ac turpis egestas. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Justo donec enim diam vulputate ut. Viverra orci sagittis eu volutpat odio. Eget magna fermentum iaculis eu non diam phasellus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Quis risus sed vulputate odio ut enim blandit. Commodo viverra maecenas accumsan lacus vel facilisis. Velit egestas dui id ornare arcu odio ut sem nulla. Sed sed risus pretium quam vulputate dignissim suspendisse. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Placerat vestibulum lectus mauris ultrices. A lacus vestibulum sed arcu non odio euismod. Elit scelerisque mauris pellentesque pulvinar pellentesque. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. At in tellus integer feugiat scelerisque. Amet justo donec enim diam vulputate ut pharetra sit amet. Ac auctor augue mauris augue.</p>

                                <ReportImage/>
                                <p class="fw-normal lh-base">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Erat imperdiet sed euismod nisi porta. Amet purus gravida quis blandit turpis cursus. Consectetur adipiscing elit ut aliquam purus sit amet. Varius morbi enim nunc faucibus a. Bibendum est ultricies integer quis. Mauris augue neque gravida in fermentum et sollicitudin ac orci. Tincidunt eget nullam non nisi. Eu scelerisque felis imperdiet proin fermentum leo vel. Volutpat est velit egestas dui. Blandit cursus risus at ultrices mi tempus imperdiet nulla malesuada. Eu turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Magna fringilla urna porttitor rhoncus dolor purus non. Ornare suspendisse sed nisi lacus sed viverra tellus in. Vitae aliquet nec ullamcorper sit.</p>
                                
                            <p class="fw-normal lh-base">In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Convallis aenean et tortor at risus viverra adipiscing at. Morbi tristique senectus et netus et. Imperdiet massa tincidunt nunc pulvinar. Habitant morbi tristique senectus et netus et malesuada. Laoreet sit amet cursus sit amet dictum. Proin sed libero enim sed faucibus. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Pellentesque dignissim enim sit amet venenatis urna cursus eget. Pellentesque id nibh tortor id. Lectus nulla at volutpat diam ut venenatis. Curabitur vitae nunc sed velit dignissim sodales ut eu.</p>

                            <p class="fw-normal lh-base">Porttitor lacus luctus accumsan tortor posuere ac ut consequat. Aliquam ut porttitor leo a diam. Sit amet facilisis magna etiam tempor orci eu lobortis. Facilisis sed odio morbi quis. Ac felis donec et odio pellentesque diam volutpat. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Gravida quis blandit turpis cursus in hac habitasse. Id consectetur purus ut faucibus. Tellus cras adipiscing enim eu turpis egestas. Enim lobortis scelerisque fermentum dui faucibus in ornare. Et leo duis ut diam quam nulla porttitor massa id.</p>

                            <p class="fw-normal lh-base">Bibendum arcu vitae elementum curabitur vitae nunc sed. Praesent semper feugiat nibh sed. Tristique magna sit amet purus gravida quis blandit turpis cursus. In tellus integer feugiat scelerisque varius morbi. Sed faucibus turpis in eu mi bibendum neque. Ornare lectus sit amet est placerat in egestas erat imperdiet. Enim nunc faucibus a pellentesque sit amet. At quis risus sed vulputate odio. Neque ornare aenean euismod elementum nisi quis eleifend quam. Fermentum odio eu feugiat pretium nibh ipsum. Leo vel fringilla est ullamcorper eget nulla. Amet nulla facilisi morbi tempus. Est pellentesque elit ullamcorper dignissim cras. Ut morbi tincidunt augue interdum velit euismod. Ultrices eros in cursus turpis massa tincidunt. Leo vel fringilla est ullamcorper eget nulla. Ullamcorper a lacus vestibulum sed. Ipsum a arcu cursus vitae congue mauris rhoncus. Malesuada fames ac turpis egestas maecenas pharetra convallis. Aliquet nibh praesent tristique magna sit amet.</p>

                            <p class="fw-normal lh-base">Lectus mauris ultrices eros in cursus turpis massa tincidunt dui. Nunc mattis enim ut tellus elementum. Sed turpis tincidunt id aliquet risus feugiat in ante. Ut venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Donec enim diam vulputate ut. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Scelerisque purus semper eget duis at tellus. Feugiat in ante metus dictum at tempor commodo. Nulla malesuada pellentesque elit eget gravida. Mi sit amet mauris commodo. Sapien eget mi proin sed libero enim sed faucibus. At risus viverra adipiscing at in tellus integer feugiat scelerisque. At erat pellentesque adipiscing commodo elit at imperdiet dui. At erat pellentesque adipiscing commodo. Vitae elementum curabitur vitae nunc sed velit dignissim sodales. Sapien nec sagittis aliquam malesuada bibendum arcu vitae. Risus quis varius quam quisque id diam vel. Platea dictumst vestibulum rhoncus est pellentesque elit.</p>

                            <p class="fw-normal lh-base">Tristique senectus et netus et malesuada fames ac turpis egestas. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Justo donec enim diam vulputate ut. Viverra orci sagittis eu volutpat odio. Eget magna fermentum iaculis eu non diam phasellus. Amet facilisis magna etiam tempor orci eu lobortis elementum nibh. Quis risus sed vulputate odio ut enim blandit. Commodo viverra maecenas accumsan lacus vel facilisis. Velit egestas dui id ornare arcu odio ut sem nulla. Sed sed risus pretium quam vulputate dignissim suspendisse. Et netus et malesuada fames ac turpis egestas maecenas pharetra. Donec ac odio tempor orci dapibus ultrices in iaculis nunc. Placerat vestibulum lectus mauris ultrices. A lacus vestibulum sed arcu non odio euismod. Elit scelerisque mauris pellentesque pulvinar pellentesque. Sapien et ligula ullamcorper malesuada proin libero nunc consequat. At in tellus integer feugiat scelerisque. Amet justo donec enim diam vulputate ut pharetra sit amet. Ac auctor augue mauris augue.</p>

                            <p class="fw-normal lh-base">Semper auctor neque vitae tempus quam pellentesque. Ultricies tristique nulla aliquet enim tortor at auctor. Morbi tristique senectus et netus et malesuada fames ac turpis. Eu lobortis elementum nibh tellus molestie. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Sagittis vitae et leo duis ut diam. Fames ac turpis egestas integer. Egestas quis ipsum suspendisse ultrices gravida dictum fusce. In eu mi bibendum neque egestas congue quisque. Enim sit amet venenatis urna cursus. Elementum sagittis vitae et leo. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Neque aliquam vestibulum morbi blandit. Sodales ut eu sem integer vitae justo. Tristique sollicitudin nibh sit amet commodo nulla facilisi.</p>
                        </figure>
                        <hr class="bg-secondary border-2 border-top border-secondary"></hr>
                        <figure class="text-start border border-light border-2 my-3">
                            <h6><img class="rounded-circle shadow my-3 mx-3" src="http://lavinephotography.com.au/wp-content/uploads/2017/01/PROFILE-Photography-112.jpg" alt="Profile picture" style={{"width": "80px", "height": "80px"}}></img> Reporter Bella</h6>
                        </figure>


                    </div>
                    <div class="col-2">

                    </div>
                </div>
            </div>
        </div>
    );
}